apiVersion: apps/v1
kind: Deployment
metadata:
  name: lcserviceregistry
spec:
  selector:
    matchLabels:
      app: lcserviceregistry
  template:
    metadata:
      labels:
        app: lcserviceregistry
    spec:
      containers:
        - name: lcserviceregistry
          image: haiderrizvi1441/lcserviceregistry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
